### ISSUE TITLE
ngron Authtoken and more questions

### ISSUE THREAD

**Issue by StarfighterJ** [pparedes1/alexa-lgtv-remote#2]
I gave up on trying to get this to work on AWS for a bit. 
Any way I get the Accept on tv when I npm run start using node.js running on a Windows 10 Computer.
I want to try and do it your way before I go back to AWS so I get a better understanding on what the program does and how Alexa ECHO will respond with the Program.
what Do I do with ngron?

**Comment by pparedes1** [comment]
Hi, if you’ve gotten the app running locally, let’s say on port 3000, on another prompt you can run 

> ngrok http 3000

This should give you an https address you can use as an endpoint to test. I’m assuming your pc and tv are on the same subnet?

Once you’ve accepted the request on tv, it stores the authorization locally and you shouldn’t get again (unless you delete the key on your pc).

**Comment by pparedes1** [comment]
One tip per the [readme](https://github.com/pparedes1/alexa-lgtv-remote), use the below format in the Endpoint configuration for the custom Amazon Alexa skill. 

> https://<id>.ngrok.io/lgtv-remote

where <id> is what ngrok gives you when run against the http request on the port specified (3000 in the example above).

**Comment by pparedes1** [comment]
Will close for now as it seems you've gotten the ngrok issue working, can reopen as needed.
